### ISSUE TITLE
No newline before "Cel:" in TestCasesEDIT.md

### ISSUE THREAD

**Issue by oskarkulinski** [oskarkulinski/Cosmic-tests#30]
Newlines should be added before "Cel:" in TestCasesEDIT.md

**Comment by wienio03** [comment]
Terrible bug... requires quick fixing.

**Comment by oskarkulinski** [comment]
![image](https://github.com/user-attachments/assets/bf713f97-7537-4e87-a836-64896f5e41b5)

**Comment by filiera** [comment]
fixed
